CREATE TABLE MESSAGE
(
    ID REAL NOT NULL,
    MESSAGE TEXT
);
CREATE UNIQUE INDEX sqlite_autoindex_MESSAGE_1 ON MESSAGE (ID);
CREATE TABLE SEQUENCE
(
    SEQ_NAME TEXT NOT NULL,
    SEQ_COUNT REAL
);
CREATE UNIQUE INDEX sqlite_autoindex_SEQUENCE_1 ON SEQUENCE (SEQ_NAME);